name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Cargo Deny
        run: cargo install cargo-deny
      - name: Install Tcl/Tk
        run: sudo apt-get install tcl-dev tk-dev
      - name: Deny
        run: cargo deny --log-level=error check
      - name: Check
        run: cargo check --verbose
      - name: Lint
        run: cargo clippy -- -Dwarnings

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Windows Toolchain
        run: rustup target add x86_64-pc-windows-gnu
      - name: Install Cargo About
        run: cargo install cargo-about
      - name: Install Tcl/Tk
        run: sudo apt-get install tcl-dev tk-dev
      - name: Build
        run: ./cross_windows.sh
