name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cargo Deny
        run: cargo install cargo-deny
      - name: Tcl/Tk
        run: sudo apt-get install tcl-dev tk-dev

  check:

    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Deny
        run: cargo deny --log-level=error check
      - name: Check
        run: cargo check -vv
      - name: Lint
        run: cargo clippy -Dwarnings

  build:

    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Build
        run: ./cross_windows.sh
